formatter: "markdown" # this is required

# version: ""

header-from: "notes.md"
#footer-from: "notes.md"

recursive:
  enabled: false
  #path добавляется к working-dir из terraform-docs/gh-actions.
  path: .

# sections:
#   hide: []
#   show: []

# content: ""

output:
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

# output-values:
#   enabled: false
#   from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true